config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  root 'questions#index'

  # Concerns
  concern :pageable do
    get 'page/:page', action: 'index', on: :collection
  end

  concern :commentable do
    resources :comments, except: [:show, :index]
  end

  concern :voteable do
    post 'vote/up', to: 'votes#up'
    post 'vote/down', to: 'votes#down'
    resources :votes, only: [:index]
  end

  # Sidekiq
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # API
  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit]
      end
    end
  end

  # Search
  resource :search, only: :index do
    concerns :pageable

    get :index, to: 'search#search'
    %w[questions answers comments users].each do |type|
      get type, to: 'search#search', type: type, as: type
    end
  end

  # Main app
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get 'users/enter-email', to: 'registrations#enter_email',
      as: 'enter_registration_email'
    post 'users/sign_up_with_email', to: 'registrations#sign_up_with_email',
      as: 'sign_up_with_email'
    post 'users/merge_accounts', to: 'registrations#merge_accounts',
      as: 'merge_accounts'
  end

  # Static Pages
  %w[faq help].each do |page|
    get page, to: "static##{page}", as: page
  end


  # Resources
  resources :questions do
    concerns :pageable, :commentable, :voteable
    resources :answers, except: [:show, :index] do
      patch 'accept', on: :member
    end
    collection do
      get 'unanswered(/page/:page)', to: 'questions#index', scope: 'unanswered',
          as: 'unanswered'
      get 'most-voted(/page/:page)', to: 'questions#index', scope: 'most_voted',
          as: 'most_voted'
      get 'featured(/page/:page)',   to: 'questions#index', scope: 'featured',
          as: 'featured'
      get 'popular(/page/:page)',    to: 'questions#index', scope: 'popular',
          as: 'popular'
    end
    resource :bounty, only: [:create, :destroy]
    get 'favor', on: :member
    post 'subscribe', on: :member, as: 'subscribe_to'
    delete 'unsubscribe', on: :member, as: 'unsubscribe_from'
  end

  resources :answers, only: [] do
    concerns :commentable, :voteable
  end

  resources :users, only: [:index, :show, :edit, :update] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#by_user',
      as: 'questions'
    get 'answers(/page/:page)',            to: 'answers#by_user',
      as: 'answers'
    get 'voted/questions(/page/:page)',    to: 'questions#voted',
      as: 'voted_questions'
    get 'voted/answers(/page/:page)',      to: 'answers#voted',
      as: 'voted_answers'
    get 'favorited/questions(/page/:page)', to: 'questions#favorited',
      as: 'favorited_questions'

    get '/reset-password', on: :member,     to: 'users#reset_password',
      as: 'reset_password_for'
  end

  resources :tags, only: [:index, :show] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#tagged',
      as: 'questions'
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable
  include Favorable
  include Timestampable

  default_scope { order(created_at: :desc) }

  enum status: [:active, :locked, :flagged, :deleted, :archived]

  belongs_to :user
  has_one :bounty, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :answers, dependent: :destroy
  has_many :comments,    as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable,  dependent: :destroy
  has_many :subscriptions, as: :subscribable,  dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user,
    class_name: User

  validates :title, presence: true, length: {in: 15..60}
  validates :body,  presence: true, length: {in: 40..6000}

  after_create  :add_author_to_subscribers
  before_destroy :decrement_tags_counter

  paginates_per 5

  is_impressionable counter_cache: true, column_name: :views_count, unique: true

  accepts_nested_attributes_for :attachments, allow_destroy: true,
    reject_if: :all_blank

  scope :unanswered, -> { where(answers_count: 0) }
  scope :popular,    -> { reorder(views_count: :desc) }
  scope :featured,   -> { joins(:bounty).where(bounties: {winner_id: nil}).
                          order('bounties.value') }
  scope :most_voted, -> { joins("LEFT OUTER JOIN votes ON "\
                          "questions.id = votes.voteable_id AND "\
                          "votes.voteable_type = 'Question'").
                          group('questions.id').
                          reorder('COALESCE(SUM(votes.value), 0) desc') }

  def self.favorited(user_id)
    joins(:favorites).where(favorites: {user_id: user_id})
  end

  def from?(user)
    user == self.user
  end

  def tag_list
    tags.pluck(:name)
  end

  def tag_list=(tags)
    new_tags = [*tags].map {|t| Tag.find_or_create_by(name: t.downcase.strip) }
    new_tags.each do |t|
      unless self.tags.include? t
        self.tags << t
        t.increment!(:questions_count)
      end
    end
    self.tags.each do |t|
      unless new_tags.include? t
        self.tags.delete(t)
        t.decrement!(:questions_count)
      end
    end
  end

  def accepted_answer
    answers.find_by_accepted(true)
  end

  def accepted?(answer)
    accepted_answer == answer
  end

  def subscribe(user)
    subscription = Subscription.new(user: user, subscribable: self)
    subscription.save!
    subscription
  end

  def unsubscribe(user)
    Subscription.delete_all(user: user, subscribable: self)
  end

  protected

  def add_author_to_subscribers
    subscribe(self.user)
  end

  def decrement_tags_counter
    self.tags.each {|t| t.decrement!(:questions_count) }
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  actions :all, except: [:new, :edit]

  load_and_authorize_resource except: [:index]

  def index
    respond_with collection, each_serializer: QuestionCollectionSerializer,
      meta: { timestamp: Question.last_timestamp }
  end

  protected

  def create_resource(object)
    object.user = current_resource_owner
    super
  end

  def question_params
    params[:question][:tag_list] ||= [] if params[:question]
    params.require(:question).permit(:title, :body, tag_list: [],
      attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  include ApplicationHelper

  respond_to :html, :js, :json

  before_action :authenticate_user!, only: [:favor, :create, :edit, :update,
    :destroy, :new, :subscribe, :unsubscribe]
  before_action :set_user, only: [:favorited, :voted, :by_user]
  before_action :set_tags, only: [:new, :edit]

  impressionist actions: [:show]

  load_and_authorize_resource except: [:index, :new]

  def subscribe
    resource.subscribe(current_user)
    respond_to do |format|
      format.html { redirect_to resource, tr(:question, 'subscribed') }
      format.js
    end
  end

  def unsubscribe
    resource.unsubscribe(current_user)
    respond_to do |format|
      format.html { redirect_to resource, tr(:question, 'unsubscribed') }
      format.js
    end
  end

  def favor
    @favored = resource.favor(current_user)
    respond_to do |format|
      format.html { redirect_to resource }
      format.json
    end
  end

  def favorited
    @questions = Question.favorited(params[:user_id]).page(params[:page])
  end

  def tagged
    @tag = Tag.find(params[:tag_id])
    @questions = @tag.questions.page(params[:page])
  end

  def voted
    @questions = Question.voted_by(params[:user_id]).page(params[:page])
  end

  def by_user
    @questions = Question.where(user_id: params[:user_id]).page(params[:page])
  end

  def show
    @question ||= end_of_association_chain.includes(
      answers: [:comments, :attachments, :user]).find(params[:id])
  end

  def create
    create!(tr(:question, 'created'))
  end


  def update
    update!(tr(:question, 'updated'))
  end

  def destroy
    destroy!(tr(:question, 'deleted'))
  end

  protected

  def create_resource(object)
    object.user = current_user
    super
  end

  def collection
    @questions ||= params[:scope] ?
      end_of_association_chain.includes(:tags, :user).send(params[:scope]).page(params[:page]) :
      end_of_association_chain.includes(:tags, :user).page(params[:page])
  end

  def resource
    @question ||= end_of_association_chain.includes(
      answers: [:comments, :attachments, :user]).find(params[:id])
  end

  def set_tags
    gon.tag_names = Tag.name_list
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def question_params
    params[:question][:tag_list] ||= [] if params[:question]
    params.require(:question).permit(:title, :body, tag_list: [],
      attachments_attributes: [:id, :file, :_destroy])
  end
end

app/views/questions/_answers.html.haml
%h3.answers-heading
  = resource.answers.count
  = t('activerecord.models.answer', count: resource.answers.count)
- resource.answers.accepted_first.each do |answer|
  - if answer.persisted?
    = render 'answers/answer', answer: answer, parent: resource

app/views/questions/_form.html.haml
- remote = resource.persisted? if remote.nil?
- resource.attachments.build

- if resource.errors.any?
  - resource.errors.full_messages.each do |error|
    %ul.errors.question-errors
      %li.alert.alert-danger= error

= form_for resource, remote: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.text_area :body, class: 'form-control'
  .form-group
    = f.label :tag_list
    = f.text_field :tag_list, class: 'form-control suggest-tag'

  = f.fields_for :attachments do |a|
    .form-group.file-upload
      - if a.object.persisted?
        = a.label :file
        = link_to a.object.file.filename, a.object.file.url
        %label.nested
          = t('common.replace_file')
          = a.file_field :file
        = a.label t('common.delete')
        = a.check_box '_destroy'
      - else
        = a.label :file
        = a.file_field :file

  .form-group
    = link_to t('attachment.add'), '#', class: "add-file btn btn-info btn-xs"

  .form-group
    = f.submit t('question.ask'), data: {disable_with: t('common.processing')}, class: 'btn btn-success'
    - if remote
      %button.cancel.btn= t('common.cancel')

:javascript
  if (typeof window.gon === 'undefined') window.gon={};
  gon.tag_names = #{Tag.name_list};

app/views/questions/_question.html.haml
%h1= resource.title

.vote-cell
  = render 'vote_cell'

.question-cell
  .question-body
    .question-meta
      %a.spoiler-btn{href: '#', data: {toggle: "collapse", target: ".meta-spoiler"}}
        %b.caret
      .meta-spoiler.collapse
        %span.views-count
          %span.glyphicon.glyphicon-eye-open
          = resource.views_count
        %span.created-ago
          %span.glyphicon.glyphicon-time
          = t('common.last_activity')
          = timeago_tag resource.updated_at, lang: I18n.locale

    .question-text
      = resource.body.html_safe

    %ul.question-files
      - resource.attachments.each do |attachment|
        - if attachment.persisted?
          %li
            %span.glyphicon.glyphicon-file
            = link_to attachment.file.filename, attachment.file.url

  - if resource.from?(current_user)
    #question-edit-form
      = render 'form'

  .tags
    - resource.tags.each do |tag|
      = link_to tag.name, tag

  .row.question-details
    .controls.col-sm-6
      - if resource.from?(current_user)
        = link_to t('common.edit'), [:edit, resource], class: 'edit btn btn-warning btn-xs'
        = link_to t('common.delete'), resource, class: 'delete btn btn-danger btn-xs', remote: true, method: :delete, data: { confirm: t("common.sure") }
      - elsif user_signed_in?
        - if current_user.subscribed_to?(resource)
          = link_to t('common.unsubscribe'), [:unsubscribe_from, resource], method: 'delete', class: 'unsubscribe btn btn-default btn-xs'
        - else
          = link_to t('common.subscribe'), [:subscribe_to, resource], method: 'post', class: 'subscribe btn btn-default btn-xs'

    = render 'shared/author', resource: resource

  .comments
    = render 'comments/comments', commentable: resource

  - if resource.bounty
    = render 'bounties/bounty', bounty: resource.bounty

  - if user_signed_in?
    = link_to t('comment.add'), new_question_comment_path(resource), class: 'add-comment btn btn-default btn-xs'

  - if resource.from?(current_user) && resource.bounty.nil?
    = render 'bounties/form', parent: resource

    = link_to t('bounty.start'), '#', class: 'start-bounty btn btn-default btn-xs'

app/views/questions/_vote_cell.html.haml
= link_to_vote_for(resource, :up) do
  .text= vote_text(resource, :up)

.vote-sum= resource.vote_sum

= link_to_vote_for(resource, :down) do
  .text= vote_text(resource, :down)

= add_to_favorites_link(resource) do
  .text= resource.favored_by?(current_user) ? t('favorite.favored') : t('favorite.favor')

app/views/questions/by_user.html.haml
%h1
  = t('user.questions')
  = link_to @user.name, @user

#questions
  = render 'list', questions: @questions

app/views/questions/create.js.erb
<% if resource.errors.empty? %>
  <% flash[:notice] = tr_raw(:question, 'created') %>
  window.location.href = '<%= question_path(@question) %>'

  <% publish_to '/questions' do %>
    $('#questions').prepend(
      '<%= j render 'questions/list_item', question: @question %>'
    );
    $('#questions .question').last().remove();
    $('<%= class_with_id(@question) %>').css('background-color', '#fffff7');
    $('<%= class_with_id(@question) %>').find('.controls').hide();
    if ($("header .user-name").data('user-id') == <%= @question.user.id %>) {
      $('<%= class_with_id(@question) %>').find('.controls').show();
    }
  <% end %>
<% else %>
  $('#new-question-form').html(
    '<%= j render 'questions/form', question: @question %>'
  );
  $('.suggest-tag').magicSuggest({
    required: true,
    useTabKey: true,
    useCommaKey: true,
    useZebraStyle: true,
    inputCfg: {"id":'tag-suggest-input'},
    data: <%= Tag.name_list.to_s.html_safe %>
  });
<% end %>

app/views/questions/destroy.js.erb
<% flash[:notice] = tr_raw(:question, 'deleted') %>
window.location.href = '<%= questions_path %>'

<% publish_to "/questions" do %>
  $('<%= class_with_id(resource) %>').remove();
<% end %>

app/views/questions/edit.html.haml
%h1= t('question.edit')

#question-edit-form.question
  = render 'questions/form', remote: false

app/views/questions/favorite.html.haml
%h1= "#{t('user.questions')} #{@user.name}"

#questions
  = render 'list', questions: @questions

app/views/questions/index.html.haml
- content_for :title do
  = t('activerecord.models.question.other')

%header.questions
  %h1= t('activerecord.models.question.other')

  .question-nav.btn-group
    = link_to t('question.newest'),     questions_path, class: 'btn btn-default' + cp(questions_path)
    = link_to t('question.unanswered'), unanswered_questions_path, class: 'btn btn-default' + cp(unanswered_questions_path)
    = link_to t('question.popular'),    popular_questions_path, class: 'btn btn-default' + cp(popular_questions_path)
    = link_to t('question.most_voted'), most_voted_questions_path, class: 'btn btn-default' + cp(most_voted_questions_path)
    = link_to t('question.featured'),   featured_questions_path, class: 'btn btn-default' + cp(featured_questions_path)

#questions
  = render 'list', questions: collection

= content_for :subscriptions do
  = subscribe_to questions_with_scope_path

app/views/questions/new.html.haml
- content_for :title do
  = t('common.new')
  = t('activerecord.models.question.one')

%h1= t('question.create')

#new-question-form.question
  = render 'form'

app/views/questions/show.html.haml
- content_for :title do
  = t('activerecord.models.question.one')
  = resource.title

.question{id: "question-#{resource.id}"}
  = render 'question'

#answers
  = render 'answers'

#new-answer-form
  %h2= t('answer.your')
  = render 'answers/form', answer: resource.answers.build

- unless user_signed_in?
  #login-form
    %h4= t('user.login_to_answer')
    =render 'users/login_form'

  #registration-form
    = link_to t('user.register'), new_user_registration_path

= render 'comments/form', commentable: resource, comment: resource.comments.build, edit: true

= content_for :subscriptions do
  = subscribe_to "/questions/#{resource.id}/answers"
  = subscribe_to "/questions/#{resource.id}/comments"

app/views/questions/update.js.erb
<% if resource.errors.empty? %>
  $('#content').prepend(
    '<%= j render 'shared/flash',  flash: tr(:question, 'updated') %>'
  );

  <% if remotipart_submitted? %>
    $('.question').html("<%= j "#{render 'questions/question'}" %>");
  <% else %>
    $('.question').html("<%= j render 'questions/question' %>");
  <% end %>

  $('#question-<%= @question.id %> .question-body')
    .css('background-color', '#e0e0e0');
<% else %>
  $('#question-<%= @question.id %> form').replaceWith(
    '<%= j render 'questions/form' %>'
  );
<% end %>

app/views/questions/voted.html.haml
%h1= "#{t('user.voted_answers')} #{@user.name}"

#questions
  = render 'list', questions: @questions