config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  root 'questions#index'

  # Concerns
  concern :pageable do
    get 'page/:page', action: 'index', on: :collection
  end

  concern :commentable do
    resources :comments, except: [:show, :index]
  end

  concern :voteable do
    post 'vote/up', to: 'votes#up'
    post 'vote/down', to: 'votes#down'
    resources :votes, only: [:index]
  end

  # Sidekiq
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # API
  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit]
      end
    end
  end

  # Search
  resource :search, only: :index do
    concerns :pageable

    get :index, to: 'search#search'
    %w[questions answers comments users].each do |type|
      get type, to: 'search#search', type: type, as: type
    end
  end

  # Main app
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get 'users/enter-email', to: 'registrations#enter_email',
      as: 'enter_registration_email'
    post 'users/sign_up_with_email', to: 'registrations#sign_up_with_email',
      as: 'sign_up_with_email'
    post 'users/merge_accounts', to: 'registrations#merge_accounts',
      as: 'merge_accounts'
  end

  # Static Pages
  %w[faq help].each do |page|
    get page, to: "static##{page}", as: page
  end


  # Resources
  resources :questions do
    concerns :pageable, :commentable, :voteable
    resources :answers, except: [:show, :index] do
      patch 'accept', on: :member
    end
    collection do
      get 'unanswered(/page/:page)', to: 'questions#index', scope: 'unanswered',
          as: 'unanswered'
      get 'most-voted(/page/:page)', to: 'questions#index', scope: 'most_voted',
          as: 'most_voted'
      get 'featured(/page/:page)',   to: 'questions#index', scope: 'featured',
          as: 'featured'
      get 'popular(/page/:page)',    to: 'questions#index', scope: 'popular',
          as: 'popular'
    end
    resource :bounty, only: [:create, :destroy]
    get 'favor', on: :member
    post 'subscribe', on: :member, as: 'subscribe_to'
    delete 'unsubscribe', on: :member, as: 'unsubscribe_from'
  end

  resources :answers, only: [] do
    concerns :commentable, :voteable
  end

  resources :users, only: [:index, :show, :edit, :update] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#by_user',
      as: 'questions'
    get 'answers(/page/:page)',            to: 'answers#by_user',
      as: 'answers'
    get 'voted/questions(/page/:page)',    to: 'questions#voted',
      as: 'voted_questions'
    get 'voted/answers(/page/:page)',      to: 'answers#voted',
      as: 'voted_answers'
    get 'favorited/questions(/page/:page)', to: 'questions#favorited',
      as: 'favorited_questions'

    get '/reset-password', on: :member,     to: 'users#reset_password',
      as: 'reset_password_for'
  end

  resources :tags, only: [:index, :show] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#tagged',
      as: 'questions'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:type]
      model = params[:type][0..-2].capitalize.constantize
      @results = model.search params[:q], page: params[:page]
    else
      @results = ThinkingSphinx.search params[:q], page: params[:page]
    end
  end
end

app/views/search/search.html.haml
%h1= t("search.results")
%p
  = t('search.you_searched', for: params[:q]).html_safe

.search-nav.btn-group
  = link_to t('common.all'), search_path(q: params[:q]), class: 'btn btn-default' + cp(search_path)
  = link_to t('activerecord.models.question.other'), questions_search_path(q: params[:q]), class: 'btn btn-default' + cp(questions_search_path)
  = link_to t('activerecord.models.answer.other'), answers_search_path(q: params[:q]), class: 'btn btn-default' + cp(answers_search_path)
  = link_to t('activerecord.models.comment.other'), comments_search_path(q: params[:q]), class: 'btn btn-default' + cp(comments_search_path)
  = link_to t('activerecord.models.user.other'), users_search_path(q: params[:q]), class: 'btn btn-default' + cp(users_search_path)

.search-results
  - if @results.any?
    .results-count
      = t("search.found", results: @results.count).html_safe

    %ol{start: search_counter_start}
      - @results.each do |result|
        %li.result
          .h3= link_to search_link_title(result), search_link(result)
          %p= search_body(result).html_safe

  - else
    %p= t("search.no_results")

= t("search.found", results: @results.count).html_safe
= paginate @results