config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  root 'questions#index'

  # Concerns
  concern :pageable do
    get 'page/:page', action: 'index', on: :collection
  end

  concern :commentable do
    resources :comments, except: [:show, :index]
  end

  concern :voteable do
    post 'vote/up', to: 'votes#up'
    post 'vote/down', to: 'votes#down'
    resources :votes, only: [:index]
  end

  # Sidekiq
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # API
  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit]
      end
    end
  end

  # Search
  resource :search, only: :index do
    concerns :pageable

    get :index, to: 'search#search'
    %w[questions answers comments users].each do |type|
      get type, to: 'search#search', type: type, as: type
    end
  end

  # Main app
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get 'users/enter-email', to: 'registrations#enter_email',
      as: 'enter_registration_email'
    post 'users/sign_up_with_email', to: 'registrations#sign_up_with_email',
      as: 'sign_up_with_email'
    post 'users/merge_accounts', to: 'registrations#merge_accounts',
      as: 'merge_accounts'
  end

  # Static Pages
  %w[faq help].each do |page|
    get page, to: "static##{page}", as: page
  end


  # Resources
  resources :questions do
    concerns :pageable, :commentable, :voteable
    resources :answers, except: [:show, :index] do
      patch 'accept', on: :member
    end
    collection do
      get 'unanswered(/page/:page)', to: 'questions#index', scope: 'unanswered',
          as: 'unanswered'
      get 'most-voted(/page/:page)', to: 'questions#index', scope: 'most_voted',
          as: 'most_voted'
      get 'featured(/page/:page)',   to: 'questions#index', scope: 'featured',
          as: 'featured'
      get 'popular(/page/:page)',    to: 'questions#index', scope: 'popular',
          as: 'popular'
    end
    resource :bounty, only: [:create, :destroy]
    get 'favor', on: :member
    post 'subscribe', on: :member, as: 'subscribe_to'
    delete 'unsubscribe', on: :member, as: 'unsubscribe_from'
  end

  resources :answers, only: [] do
    concerns :commentable, :voteable
  end

  resources :users, only: [:index, :show, :edit, :update] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#by_user',
      as: 'questions'
    get 'answers(/page/:page)',            to: 'answers#by_user',
      as: 'answers'
    get 'voted/questions(/page/:page)',    to: 'questions#voted',
      as: 'voted_questions'
    get 'voted/answers(/page/:page)',      to: 'answers#voted',
      as: 'voted_answers'
    get 'favorited/questions(/page/:page)', to: 'questions#favorited',
      as: 'favorited_questions'

    get '/reset-password', on: :member,     to: 'users#reset_password',
      as: 'reset_password_for'
  end

  resources :tags, only: [:index, :show] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#tagged',
      as: 'questions'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  AVATAR_SIZE = { micro: 16, thumb: 32, medium: 128, large: 512 }

  default_scope { order('reputation ASC, created_at DESC') }

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:facebook, :twitter]

  has_one :profile, dependent: :destroy
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
  has_many :voted_questions, through: :votes, source: :voteable,
    source_type: "Question"
  has_many :voted_answers, through: :votes, source: :voteable,
    source_type: "Answer"
  has_many :favorites, dependent: :destroy
  has_many :authorizations, dependent: :destroy

  attr_accessor :login

  accepts_nested_attributes_for :profile

  delegate :real_name, :website, :location, :birthday, :about, to: :profile

  validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {in: 3..30}
  validates :email, uniqueness: { case_sensitive: false },
    length: {maximum: 254}, format: {with: Devise.email_regexp}

  after_create :set_profile

  mount_uploader :avatar, AvatarUploader

  paginates_per 5

  # Authenticate by email or login
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.find_for_oauth(auth, current_user=nil)
    authorization = Authorization.find_for_oauth(auth)
    return authorization.user if authorization

    email = auth.info.email
    return User.new unless email

    user = User.find_by_email(email)
    if user.nil?
      password = Devise.friendly_token[0,10]
      name = User.unique_name(auth.info.nickname)
      user = User.create! name: name, email: email, password: password,
        password_confirmation: password
    end

    user.authorizations.create(provider: auth.provider, uid: auth.uid.to_s)
    user
  end

  def self.build_from_email_and_session(params, session)
    name = User.unique_name session.info.nickname
    password = Devise.friendly_token[0,10]
    user = User.new(email: params[:email],  name: name, password: password,
      password_confirmation: password)
    user.authorizations.build(provider: session.provider, uid: session.uid.to_s)
    user
  end

  def self.unique_name(name)
    unique_name = name
    i = 2
    while find_by_name(unique_name) do
      unique_name = name + i.to_s
      i += 1
    end
    unique_name
  end

  def self.send_daily_digest
    select(:id).find_each do |user|
      DailyMailer.delay.digest(user.id) if user.try(:daily_digest)
    end
  end


  def create_authorization(auth)
    authorizations.find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

  def set_profile
    self.create_profile
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.name || self.email
  end

  def subscribed_to?(resource)
    !!Subscription.where(user: self, subscribable: resource).first
  end

  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  def voted(object)
    votes = {1 => :up,-1 => :down}
    votes[get_vote_for(object).try(:value)]
  end

  def get_vote_for(object)
    votes.where(voteable_id: object.id, voteable_type: object.class).first
  end

  def favorited(object)
    favorites.where(favorable_id: object.id, favorable_type: object.class).first
  end

  def avatar_url(size=:thumb)
    avatar.url ? avatar.url(size) : gravatar_url(size)
  end

  private

  def gravatar_url(size)
    # default_url = "#{root_url}/images/avatar-default-#{AVATAR_SIZE[size]}.jpg"
    default_url = "http://riabit.ru/avatar-default-#{AVATAR_SIZE[size]}.jpg"
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?"\
      "s=#{AVATAR_SIZE[size]}&d=#{CGI.escape(default_url)}"
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def me
    respond_with current_resource_owner
  end

  def index
    respond_with collection#.to_json(except: :admin, include: :profile)
  end

  protected

  def collection
    @users ||= end_of_association_chain.includes(:profile)
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  include ApplicationHelper

  respond_to :html
  actions :index, :show, :edit, :update
  custom_actions resource: :reset_password

  before_action :authenticate_user!, only: [:edit, :update, :reset_password]

  load_and_authorize_resource except: :index

  def update
    update! tr(:profile, 'updated') { resource }
  end

  def reset_password
    resource.send_reset_password_instructions
    redirect_to root_path, notice: t('devise.passwords.send_instructions')
  end

  protected

  def collection
    @users ||= end_of_association_chain.page(params[:page])
  end

  def user_params
    params.require(:user).permit(:avatar, profile_attributes: [:id, :real_name,
      :website, :location, :birthday, :about, :_destroy])
  end
end

app/views/users/_form.html.haml
%ul.errors.question-errors
- if resource.profile.errors.any?
  - resource.profile.errors.full_messages.each do |error|
    %li.alert.alert-danger= error
- if resource.errors.any?
  - resource.errors.full_messages.each do |error|
    %li.alert.alert-danger= error

= form_for resource, role: 'form' do |f|
  .form-group
    = f.label :avatar
    = f.file_field :avatar
    = image_tag resource.avatar_url(:medium), class: 'avatar'

  = f.fields_for :profile do |p|
    .form-group
      = p.label :real_name
      = p.text_field :real_name, class: 'form-control'
    .form-group
      = p.label :website
      = p.text_field :website, class: 'form-control'
    .form-group
      = p.label :location
      = p.text_field :location, class: 'form-control'
    .form-group
      = p.label :birthday
      = p.date_select :birthday, class: 'form-control'
    .form-group
      = p.label :about
      = p.text_area :about, class: 'form-control'

  = f.submit t('common.save'), data: {disable_with: t('common.processing')}, class: 'btn btn-success'

app/views/users/_login_form.html.haml
= form_for User.new, url: new_user_session_path, role: "form" do |f|
  .form-group
    = f.label :email
    = f.email_field :email, class: "form-control", autofocus: true
  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control", autocomplete: "off"
  - if Devise.mappings[:user].rememberable?
    .form-group
      = f.check_box :remember_me
      = f.label :remember_me
  = f.submit t('user.log_in'), class: 'btn btn-primary'

app/views/users/edit.html.haml
%h1
  = t('user.edit')
  = link_to resource.name, resource

= link_to t('user.reset_password'), reset_password_for_user_path, class: 'btn btn-warning'

= render 'form'

app/views/users/index.html.haml
- content_for :title do
  = t('activerecord.models.user.other')

%h1= t('activerecord.models.user.other')

#users
  - collection.each do |user|
    .user
      = link_to user do
        = image_tag user.avatar_url(:thumb), class: 'avatar'
      %h3= link_to user.name, user


= paginate collection

app/views/users/show.html.haml
- content_for :title do
  = t('activerecord.models.user.one')
  = resource.name

#user
  %h1
    = t('activerecord.models.user.one')
    = resource.name

  .user-basic-details
    = image_tag resource.avatar_url(:medium), class: 'avatar'

    .user-reputation
      %h3= t('activerecord.attributes.user.reputation')
      %p= resource.reputation

  .row
    .col-sm-6
      %h2= t('user.private')
      %table
        %tr
          %td= t('activerecord.attributes.user.real_name')
          %td= resource.real_name
        - if resource == current_user
          %tr
            %td= t('activerecord.attributes.user.email')
            %td= resource.email

      %h2= t('user.bio')
      %table
        %tr
          %td= t('activerecord.attributes.user.website')
          %td= resource.website
        %tr
          %td= t('activerecord.attributes.user.location')
          %td= resource.location
        %tr
          %td= t('user.age')
          %td= timeago_tag resource.birthday, lang: I18n.locale if resource.birthday

      %h2= t('user.visits')
      %table
        %tr
          %td= t('user.member_for')
          %td= timeago_tag resource.created_at, lang: I18n.locale
        %tr
          %td= t('user.visited')
          %td= "#{resource.sign_in_count} #{t('time.times')}"
          / visited   485 days, 6 consecutive
        %tr
          %td= t('user.seen')
          %td= timeago_tag resource.current_sign_in_at, lang: I18n.locale
          / seen  1 min ago

      %h2= t('user.stats')
      %table
        %tr
          %td= t('user.profile_views')
          %td= distance_of_time_in_words(resource.created_at, Time.now)
          / profile views   46
        %tr
          %td= t('user.helpful_flags')
          %td= distance_of_time_in_words(resource.created_at, Time.now)
          / helpful flags   1

    .col-sm-6
      %h3= t('activerecord.attributes.user.about')
      .about
        = resource.about

    .col-sm-6
      %h2
        = link_to user_questions_path(resource) do
          = resource.questions.count
          = t('activerecord.models.question', count: resource.questions.count)
      %h2
        = link_to user_answers_path(resource) do
          = resource.answers.count
          = t('activerecord.models.answer', count: resource.answers.count)

      %h2= t('vote.voting')
      %h4= link_to t('activerecord.models.question.other'), [resource, :voted, :questions]
      %h4= link_to t('activerecord.models.answer.other'), [resource, :voted, :answers]

      %h2= t('user.favorites')
      %h4= link_to t('activerecord.models.question.other'), [resource, :favorited, :questions]

  - if resource == current_user
    .row.submit
      .col-sm-12
        = link_to t('common.edit'), edit_user_path(resource), class: 'btn btn-primary'