config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  root 'questions#index'

  # Concerns
  concern :pageable do
    get 'page/:page', action: 'index', on: :collection
  end

  concern :commentable do
    resources :comments, except: [:show, :index]
  end

  concern :voteable do
    post 'vote/up', to: 'votes#up'
    post 'vote/down', to: 'votes#down'
    resources :votes, only: [:index]
  end

  # Sidekiq
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # API
  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit]
      end
    end
  end

  # Search
  resource :search, only: :index do
    concerns :pageable

    get :index, to: 'search#search'
    %w[questions answers comments users].each do |type|
      get type, to: 'search#search', type: type, as: type
    end
  end

  # Main app
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get 'users/enter-email', to: 'registrations#enter_email',
      as: 'enter_registration_email'
    post 'users/sign_up_with_email', to: 'registrations#sign_up_with_email',
      as: 'sign_up_with_email'
    post 'users/merge_accounts', to: 'registrations#merge_accounts',
      as: 'merge_accounts'
  end

  # Static Pages
  %w[faq help].each do |page|
    get page, to: "static##{page}", as: page
  end


  # Resources
  resources :questions do
    concerns :pageable, :commentable, :voteable
    resources :answers, except: [:show, :index] do
      patch 'accept', on: :member
    end
    collection do
      get 'unanswered(/page/:page)', to: 'questions#index', scope: 'unanswered',
          as: 'unanswered'
      get 'most-voted(/page/:page)', to: 'questions#index', scope: 'most_voted',
          as: 'most_voted'
      get 'featured(/page/:page)',   to: 'questions#index', scope: 'featured',
          as: 'featured'
      get 'popular(/page/:page)',    to: 'questions#index', scope: 'popular',
          as: 'popular'
    end
    resource :bounty, only: [:create, :destroy]
    get 'favor', on: :member
    post 'subscribe', on: :member, as: 'subscribe_to'
    delete 'unsubscribe', on: :member, as: 'unsubscribe_from'
  end

  resources :answers, only: [] do
    concerns :commentable, :voteable
  end

  resources :users, only: [:index, :show, :edit, :update] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#by_user',
      as: 'questions'
    get 'answers(/page/:page)',            to: 'answers#by_user',
      as: 'answers'
    get 'voted/questions(/page/:page)',    to: 'questions#voted',
      as: 'voted_questions'
    get 'voted/answers(/page/:page)',      to: 'answers#voted',
      as: 'voted_answers'
    get 'favorited/questions(/page/:page)', to: 'questions#favorited',
      as: 'favorited_questions'

    get '/reset-password', on: :member,     to: 'users#reset_password',
      as: 'reset_password_for'
  end

  resources :tags, only: [:index, :show] do
    concerns :pageable
    get 'questions(/page/:page)',          to: 'questions#tagged',
      as: 'questions'
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable
  include Timestampable

  default_scope { order(created_at: :asc) }
  scope :accepted_first, -> { reorder('accepted DESC, created_at ASC') }

  belongs_to :user
  belongs_to :question, counter_cache: true, touch: true
  has_one :bounty, foreign_key: 'winner_id'
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true,
    reject_if: :all_blank

  validates :body, presence: true, length: {in: 30..6000}

  paginates_per 5

  after_create :notify_question_subscribers

  def from?(user)
    user == self.user
  end

  def toggle_accepted_from(question)
    toggle(:accepted).save
    toggle_bounty_from question
  end

  private

  def toggle_bounty_from(question)
    return false unless question.bounty
    if self.user == question.bounty.winner # Already received bounty
      give_bounty_back_to(question)
    else
      receive_bounty_from(question)
    end
  end

  def receive_bounty_from(question)
    bounty = question.bounty
    bounty.update(winner_id: self.user.id)
    question.user.reputation -= bounty.value
    self.user.reputation     += bounty.value
  end

  def give_bounty_back_to(question)
    bounty = question.bounty
    bounty.update(winner_id: nil)
    question.user.reputation += bounty.value
    self.user.reputation     -= bounty.value
  end

  def notify_question_subscribers
    NotifySubscribersWorker.perform_async(self.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  include ApplicationHelper

  respond_to :html, :js
  belongs_to :question, optional: true
  actions :all, except: :new
  custom_actions resource: :accept, collection: :voted

  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_user, only: [:voted, :by_user]

  load_and_authorize_resource

  def accept
    resource.toggle_accepted_from parent
    respond_to do |format|
      format.html { redirect_to parent }
      format.js
    end
  end

  def voted
    @answers = Answer.voted_by(params[:user_id])
  end

  def by_user
    @answers = Answer.where(user_id: params[:user_id]).
      includes(:user, :question).page(params[:page])
  end

  def create
    create!(tr(:answer, 'created')) { parent_url }
  end

  def update
    update!(tr(:answer, 'updated')) { parent_url }
  end

  def destroy
    destroy!(tr(:answer, 'deleted')) { parent_url }
  end

  protected

  def create_resource(object)
    object.user = current_user
    super
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id,
      attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  belongs_to :question, parent_class: Question, optional: true
  actions :all, except: [:new, :edit]

  load_and_authorize_resource

  def index
    respond_with collection, meta: { timestamp: Answer.last_timestamp }
  end

  protected

  def create_resource(object)
    object.user = current_resource_owner
    super
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id,
      attachments_attributes: [:id, :file, :_destroy])
  end
end

app/views/answers/_answer.html.haml
.answer{id: "answer-#{answer.id}", class: item_class(answer)}
  .vote-cell

    = link_to_vote_for(answer, :up) do
      .text= vote_text(answer, :up)

    .vote-sum= answer.vote_sum

    = link_to_vote_for(answer, :down) do
      .text= vote_text(answer, :down)

    - if parent.user == current_user
      = link_to [:accept, parent, answer], remote: true, method: 'patch', class: accept_link_class(parent, answer), title: parent.accepted?(answer) ? t('answer.best') : t('answer.choose') do
        %span.glyphicon.glyphicon-ok
        %span.text= parent.accepted?(answer) ? t('answer.best') : t('answer.choose')
    - elsif parent.accepted?(answer)
      .accept.accepted
        %span.glyphicon.glyphicon-ok
        %span.text= t('answer.best')

  .answer-cell
    .answer-body
      .answer-text= answer.body.html_safe
      %ul.answer-files
        - answer.attachments.each do |attachment|
          - if attachment.persisted?
            %li
              %span.glyphicon.glyphicon-file
              = link_to attachment.file.filename, attachment.file.url

    - if answer.from?(current_user)
      .answer-edit-form
        = render 'answers/form', answer: answer

    .row.answer-details
      .controls.col-sm-6
        - if answer.from?(current_user)
          = link_to t('common.edit'), [:edit, parent, answer], class: 'edit btn btn-warning btn-xs', data: {answer_id: answer.id}
          = link_to t('common.delete'), [parent, answer], class: 'delete btn btn-danger btn-xs', method: :delete, data: { confirm: t("common.sure") }, remote: true
      = render 'shared/author', resource: answer

    .comments
      = render 'comments/comments', commentable: answer

    - if user_signed_in?
      = link_to t('comment.add'), new_answer_comment_path(answer), class: 'add-comment btn btn-default btn-xs'

app/views/answers/_answers.html.haml
- @question.answers.each do |answer|
  - if answer.persisted?
    .answer{id: "answer-#{answer.id}"}
      .answer-text= answer.body.html_safe
      .details
        - if @question.from?(current_user)
          .controls.col-sm-6
            = link_to t('common.edit'), edit_question_answer_path(@question, answer)
            = link_to t('common.delete'), question_answer_path(@question, answer), method: :delete
        .started.col-sm-6.pull-right
          %span.time= created_ago answer
          %span.author= link_to answer.user.name, user_path(answer.user)
          %span.author-reputation

app/views/answers/_form.html.haml
- remote = answer.persisted? if remote.nil?
- answer.attachments.build

- if answer.errors.any?
  - answer.errors.full_messages.each do |error|
    %ul.errors.answer-errors
      %li.alert.alert-danger= error

= form_for [@question, answer], remote: true do |f|
  .form-group
    = f.hidden_field :question_id, value: @question.id
    = f.text_area :body, class: "form-control"

  = f.fields_for :attachments do |a|
    .form-group.file-upload
      - if a.object.persisted?
        = a.label :file
        = link_to a.object.file.filename, a.object.file.url
        %label.nested
          = t('common.replace_file')
          = a.file_field :file
        = a.label t('common.delete')
        = a.check_box '_destroy'
      - else
        = a.label :file
        = a.file_field :file

  .form-group
    = link_to t('attachment.add'), '#', class: "add-file btn btn-info btn-xs"

  = f.submit t('answer.post'), data: {disable_with: t('common.processing')}, class: "btn btn-success"
  - if remote
    %button.cancel.btn= t('common.cancel')

app/views/answers/_list.html.haml
- answers.each do |answer|
  - if answer.persisted?
    .answer{id: "answer-#{answer.id}", class: item_class(answer)}
      %h3
        = t('activerecord.models.question.one') + ':'
        = link_to answer.question.title, "#{question_path(answer.question)}#answer-#{answer.id}"
      .answer-body
        .answer-text= answer.body.html_safe
        .answer-text= answer.body.html_safe

      .details
        .started.col-sm-6.pull-right
          = timeago_tag answer.created_at, lang: I18n.locale
          %span.author
            = link_to answer.user do
              = image_tag answer.user.avatar_url(:thumb), class: 'avatar'
              = answer.user.name

= page_entries_info answers
= paginate answers

app/views/answers/accept.js.erb
<% if @answer.accepted %>
  $('#answer-<%= @answer.id %> .accept').addClass('accepted');
  $('#answer-<%= @answer.id %> .accept').attr(
    'title', '<%= t('answer.best') %>'
  );
  $('#answer-<%= @answer.id %> .accept .text').text(
    '<%= t('answer.best') %>'
  );
  $('#answer-<%= @answer.id %>').insertAfter($("#answers h3").first());
  $('.answer .accept').addClass('hidden');
  $('#answer-<%= @answer.id %> .accept').removeClass('hidden');
  <% if @answer.question.bounty %>
    $('.question .bounty').replaceWith(
      '<%= j render 'bounties/bounty', bounty: @answer.question.bounty %>'
    );
  <% end %>
<% else %>
  $('#answer-<%= @answer.id %> .accept').removeClass('accepted');
  $('#answer-<%= @answer.id %> .accept').attr(
    'title', '<%= t('answer.choose') %>'
  );
  $('#answer-<%= @answer.id %> .accept .text').text(
    '<%= t('answer.choose') %>'
  );
  $('.answer .accept').removeClass('hidden');
  <% if @answer.question.bounty %>
    $('.question .bounty').replaceWith(
      '<%= j render 'bounties/bounty', bounty: @answer.question.bounty %>'
    );
  <% end %>
<% end %>

app/views/answers/by_user.html.haml
%h1
  = t('user.answers')
  = link_to @user.name, @user

#answers
  = render 'list', answers: @answers

app/views/answers/create.js.erb
<% if resource.errors.empty? %>
  $('#content').prepend(
    "<%= j render 'shared/flash', flash: tr(:answer, 'created') %>"
  );
  $('#new-answer-form #answer_body').val('');
  $('#new-answer-form .answer-errors').hide();

  <% publish_to "/questions/#{parent.id}/answers" do %>
    $('.answers-heading').html(
      '<%= parent.answers.count %> ' +
      '<%= t('activerecord.models.answer', count: parent.answers.count) %>'
    );
    $('#answers').append('<%= j render 'answers/answer', answer: resource %>');
    $('#answers .answer').last().css('background-color', '#fffff7');
    $('#answer-' + <%= resource.id %>).find('.controls').hide();
    if ($("header .user-name").data('user-id') == <%= resource.user.id %>) {
      $('#answer-' + <%= resource.id %>).find('.controls').show();
    }
  <% end %>

<% else %>
  $('#new-answer-form').html('<%= j render 'answers/form', answer: resource %>');
<% end %>

app/views/answers/destroy.js.erb
$('#content').prepend(
  '<%= j render 'shared/flash', flash: tr(:answer, 'deleted') %>'
);

<% publish_to "/questions/#{parent.id}/answers" do %>
  $('.answers-heading').html(
    '<%= parent.answers.count %> ' +
    '<%= t('activerecord.models.answer', count: parent.answers.count) %>'
  );
  $('#answer-<%= resource.id %>').remove();
<% end %>

app/views/answers/edit.html.haml
%h1= t('answer.edit')

= render 'form', answer: @answer

app/views/answers/new.html.haml
%h1= t('answer.new')

= render 'form', answer: @answer

app/views/answers/update.js.erb
<% if @answer.errors.empty? %>
  $('#content').prepend(
    '<%= j render 'shared/flash', flash: tr(:answer, 'updated') %>'
  );

  <% publish_to "/questions/#{@question.id}/answers" do %>
    $('#answer-' + <%= @answer.id %>).replaceWith(
      '<%= j render 'answers/answer', answer: @answer %>'
    );
    $('#answer-' + <%= @answer.id %>).css('background-color', '#fffff7');
    $('#answer-' + <%= @answer.id %>).find('.controls').hide();
    if ($("header .user-name").data('user-id') == <%= @answer.user.id %>) {
      $('#answer-' + <%= @answer.id %>).find('.controls').show();
    }
  <% end %>
<% else %>
  $('#answer-<%= @answer.id %> form').replaceWith(
    '<%= j render 'answers/form', answer: @answer %>'
  );
<% end %>

app/views/answers/voted.html.haml
%h1= "#{t('user.voted_answers')} #{@user.name}"

#answers
  = render 'list', answers: @answers